// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// Generated file provides FirebaseOptions only.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoU3saJoBHMKl7MsnZvzRL0yy4BDyZ3c',
    appId: '1:591658447299:web:6ee9e11fb93977a6668d76',
    messagingSenderId: '591658447299',
    projectId: 'finder-app-14ea2',
    authDomain: 'finder-app-14ea2.firebaseapp.com',
    storageBucket: 'finder-app-14ea2.firebasestorage.app',
    measurementId: 'G-V6QY6J2XL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChw-Bscy7px17AtvuQ2B47K-8lBgs0MZc',
    appId: '1:591658447299:android:885f81b76b40912e668d76',
    messagingSenderId: '591658447299',
    projectId: 'finder-app-14ea2',
    storageBucket: 'finder-app-14ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnpgEXEJ8aBJSGVznQzk5WPfK2tcNbD10',
    appId: '1:591658447299:ios:533cc66a043d0928668d76',
    messagingSenderId: '591658447299',
    projectId: 'finder-app-14ea2',
    storageBucket: 'finder-app-14ea2.firebasestorage.app',
    iosBundleId: 'com.example.lost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnpgEXEJ8aBJSGVznQzk5WPfK2tcNbD10',
    appId: '1:591658447299:ios:533cc66a043d0928668d76',
    messagingSenderId: '591658447299',
    projectId: 'finder-app-14ea2',
    storageBucket: 'finder-app-14ea2.firebasestorage.app',
    iosBundleId: 'com.example.lost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ7TADA-mPnZLTH3e-DTBZUqVUO-MqMm0',
    appId: '1:591658447299:web:bd124a793e3cc3aa668d76',
    messagingSenderId: '591658447299',
    projectId: 'finder-app-14ea2',
    authDomain: 'finder-app-14ea2.firebaseapp.com',
    storageBucket: 'finder-app-14ea2.firebasestorage.app',
    measurementId: 'G-K3ZG82EX71',
  );
}
